-- CREATE OR REPLACE TRIGGER TO AUTOMATICALLY UPDATE ACCOUNT BALANCE BASED ON TRANSACTION TYPE
CREATE OR REPLACE TRIGGER trg_update_account_balance
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    -- IF THE TRANSACTION TYPE IS DEPOSIT, ADD THE AMOUNT TO THE BALANCE
    IF :NEW.tx_type = 'DEPOSIT' THEN
        UPDATE Accounts
        SET balance = balance + :NEW.amount
        WHERE account_no = :NEW.account_no;
        
    -- IF THE TRANSACTION TYPE IS WITHDRAWAL OR TRANSFER, SUBTRACT THE AMOUNT FROM THE BALANCE
    ELSIF :NEW.tx_type = 'WITHDRAWAL' OR :NEW.tx_type = 'TRANSFER' THEN
        UPDATE Accounts
        SET balance = balance - :NEW.amount
        WHERE account_no = :NEW.account_no;
    END IF;
END;
/

-- ADDING A BLANK LINE AFTER THE SLASH TO ENSURE ORACLE COMPILES IT IMMEDIATELY